htsql:
  db:
    engine: mysql
    database: openlegis
    username: api_reader
    password: openlegis
    host: 127.0.0.1
    port: 3306
tweak.autolimit:
  limit: 1000
tweak.cors:
tweak.meta:
tweak.shell.default:
tweak.override:
  excluded-tables: [assessor_parlamentar, dependente, documento_administrativo, funcionario, gabinete_atendimento, gabinete_eleitor, pessoa, protocolo, usuario, visita]

